### ISSUE TITLE
New CPAN release is needed

### ISSUE THREAD

**Issue by AlexDaniel** [bduggan/p6-grammar-prettyerrors#2]
There was an issue fixed here: https://github.com/bduggan/p6-grammar-prettyerrors/pull/1

However, there was no CPAN release after that, meaning that for users with new rakudo the module won't install without failures in tests.

**Comment by bduggan** [comment]
Thanks, just released 0.0.4

**Comment by AlexDaniel** [comment]
Thank you very much!
