### ISSUE TITLE
I couldn't get anything to parse

### ISSUE THREAD

**Issue by JJ** [bduggan/p6-grammar-prettyerrors#3]
```
grammar G does  Grammar::PrettyErrors {
token TOP     {  "*"  \h \w+ }
}
say G.parse("*  hey");
```

Just produces:

```
Rats, unable to parse anything, giving up.
Parsing error.
```

**Comment by bduggan** [comment]
The technique used by this module is wrapping the whitespace token `<ws>` -- in this case the whitespace token is never encountered (it isn't part of the grammar) -- so the module never gets a chance to increase the high water mark.  It would certainly be cool to add features to track parsing _within_ a token...ideas for how to do that would be welcome :-)

If the `\h` were declared as `<ws>`, and used implicitly by a `rule` then it would be caught -- e.g.
```
$ cat try.raku
#!/usr/bin/env raku

use Grammar::PrettyErrors;

grammar G does Grammar::PrettyErrors {

   rule TOP {  "*"  \w+ }
   token ws { <!ww> \h }

}

say G.parse("*  hey");

$ ./try.raku
--errors--
  1 │▶*  hey
       ^

Uh oh, something went wrong around line 1.
Unable to parse TOP.
```
