### ISSUE TITLE
Why not wrap any kind of token?

### ISSUE THREAD

**Issue by JJ** [bduggan/p6-grammar-prettyerrors#4]
In principle, the code that wraps the ws token uses "ws" as a constant. Why not leave it as a variable, and let the user decide what tokens to wrap? Since it's a role, it could be done via parametrization.

**Comment by bduggan** [comment]
Hmm, interesting idea...I am also making a default `ws` to wrap though in case there isn't one defined... (`my regex whitespace { <!ww> \s* }`) how would that be handled?

**Comment by JJ** [comment]
Well, maybe it could also be provided as a parameter... Or simply fail if there's none defined.

**Comment by bduggan** [comment]
sounds good!  Done.

**Comment by JJ** [comment]
Amazing! Thanks.
